# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4])
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
               [4,5,6]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],
                [2,3,4],
                [3,4,5]],
               [[4,5,6],
                [5,6,7],
                [6,7,8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1, a1.ndim, a1.dtype, a1.size, type(a1)

(array([1, 2, 3, 4]), 1, dtype('int64'), 4, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2, a2.ndim, a2.dtype, a2.size, type(a2)

(array([[1, 2, 3],
        [4, 5, 6]]), 2, dtype('int64'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3, a3.ndim, a3.dtype, a3.size, type(a3)

(array([[[1, 2, 3],
         [2, 3, 4],
         [3, 4, 5]],
 
        [[4, 5, 6],
         [5, 6, 7],
         [6, 7, 8]]]), 3, dtype('int64'), 18, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,10,3)

In [54]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(0,10, size=(7,2))
random_arr

array([[1, 6],
       [5, 2],
       [8, 7],
       [1, 9],
       [3, 9],
       [4, 8],
       [0, 9]])

In [60]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_float = np.random.random((3,5))
rand_float

array([[0.6377288 , 0.69025473, 0.57365946, 0.96723014, 0.18599061],
       [0.32478017, 0.35099979, 0.76563678, 0.37487888, 0.15773729],
       [0.57488297, 0.33998281, 0.76689811, 0.37048927, 0.70136013]])

In [63]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr2 = np.random.randint(0,10, size= (4,6))
rand_arr2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [65]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ran_arr = np.random.randint(1,10, size=(3,7))
ran_arr

# Find the unique numbers in the array you just created
np.unique(ran_arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
ran_arr

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]])

In [67]:
# Find the 0'th index of the latest array you created
ran_arr[0,0]

7

In [72]:
# Get the first 2 rows of latest array you created
ran_arr[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [76]:
# Get the first 2 values of the first 2 rows of the latest array
ran_arr[:2, :2]

array([[7, 8],
       [4, 2]])

In [81]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_array = np.random.randint(0,10, size=(3,5))
arr_one = np.ones((3,5))
rand_array, arr_one

(array([[2, 5, 1, 9, 8],
        [4, 5, 3, 9, 6],
        [8, 6, 0, 0, 8]]), array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [82]:
# Add the two arrays together
rand_array + arr_one

array([[ 3.,  6.,  2., 10.,  9.],
       [ 5.,  6.,  4., 10.,  7.],
       [ 9.,  7.,  1.,  1.,  9.]])

In [83]:
# Create another array of ones of shape (5, 3)
array_ones = np.ones((5,3))

In [84]:
# Try add the array of ones and the other most recent array together
array_ones + rand_array

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [85]:
# Create another array of ones of shape (3, 5)
arr_ones = np.ones((3,5))

In [87]:
# Subtract the new array of ones from the other most recent array
rand_array - arr_ones

array([[ 1.,  4.,  0.,  8.,  7.],
       [ 3.,  4.,  2.,  8.,  5.],
       [ 7.,  5., -1., -1.,  7.]])

In [88]:
# Multiply the ones array with the latest array
rand_array * arr_ones

array([[2., 5., 1., 9., 8.],
       [4., 5., 3., 9., 6.],
       [8., 6., 0., 0., 8.]])

In [90]:
# Take the latest array to the power of 2 using '**'
rand_array**2

array([[ 4, 25,  1, 81, 64],
       [16, 25,  9, 81, 36],
       [64, 36,  0,  0, 64]])

In [91]:
# Do the same thing with np.square()
np.square(rand_array)

array([[ 4, 25,  1, 81, 64],
       [16, 25,  9, 81, 36],
       [64, 36,  0,  0, 64]])

In [92]:
# Find the mean of the latest array using np.mean()
np.mean(rand_array)

4.933333333333334

In [93]:
# Find the maximum of the latest array using np.max()
np.max(rand_array)

9

In [94]:
# Find the minimum of the latest array using np.min()
np.min(rand_array)

0

In [95]:
# Find the standard deviation of the latest array
np.std(rand_array)

3.0652170486860397

In [97]:
# Find the variance of the latest array
np.var(rand_array)

9.395555555555555

In [100]:
# Reshape the latest array to (3, 5, 1)
rand_array = rand_array.reshape(3,5,1)

In [102]:
# Transpose the latest array
rand_array.T

array([[[2, 4, 8],
        [5, 5, 6],
        [1, 3, 0],
        [9, 9, 0],
        [8, 6, 8]]])

What does the transpose do?

In [103]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0,10, size=(3,3))
arr2 = np.random.randint(0,10, size=(3,2))

In [105]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

array([[67, 93],
       [79, 81],
       [92, 98]])

In [107]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0,10, size=(4,3))
arr4 = np.random.randint(0,10, size=(4,3))

In [108]:
# Perform a dot product on the two newest arrays you created
np.dot(arr3,arr4)

ValueError: ignored

It doesn't work. How would you fix it?

In [109]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3 = arr3.T
np.dot(arr3,arr4)

array([[92, 24,  0],
       [36, 21, 49],
       [15, 11, 15]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [110]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr5 = np.random.randint(0,10, size=(4,3))
arr6 = np.random.randint(0,10, size=(4,3))

In [111]:
# Compare the two arrays with '>'
arr5 > arr6

array([[ True,  True, False],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [112]:
# Compare the two arrays with '>='
arr5 >= arr6

array([[ True,  True,  True],
       [ True, False,  True],
       [ True, False,  True],
       [ True, False,  True]])

In [113]:
# Find which elements of the first array are greater than 7
arr5 >=7

array([[False,  True, False],
       [False, False, False],
       [ True, False, False],
       [ True, False, False]])

In [114]:
# Which parts of each array are equal? (try using '==')
arr5 == arr6

array([[False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [124]:
# Sort one of the arrays you just created in ascending order
np.sort(arr6)

array([[1, 5, 5],
       [0, 5, 8],
       [2, 3, 3],
       [2, 2, 9]])

In [125]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr6)

array([[0, 1, 2],
       [0, 2, 1],
       [0, 1, 2],
       [0, 2, 1]])

In [127]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr6)

10

In [128]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr6)

3

In [129]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr6, axis=1)

array([1, 1, 1, 1])

In [130]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr6, axis=0)

array([1, 2, 3])

In [133]:
# Create an array of normally distributed random numbers
arr = np.random.normal(size=10)
arr

array([-0.6256163 , -0.52246148,  0.0130339 ,  0.37776959,  0.0628246 ,
        0.50159637, -0.14694539,  0.18062297,  0.96481058, -1.06483115])

In [134]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr_ten = np.arange(0,100,10)
arr_ten

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.